# NumPy Matrix + Pandas Assignment


## Q1. Create a 3×3 NumPy Matrix

### Input
```
1 2 3
4 5 6
7 8 9
```

### Output
```python
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```


In [ ]:
# Write your code here

import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix)

## Q2. Multiply Matrix by 2

### Input
```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

### Output
```python
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
```


In [ ]:
# Write your code here
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix*2)

## Q3. Find Row-wise Sum

### Output
```python
[ 6 15 24]
```


In [ ]:
# Write your code here

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(np.sum(matrix, axis=1))

## Q4. Find Column-wise Sum

### Output
```python
[12 15 18]
```


In [ ]:
# Write your code here

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.sum(matrix,axis=0))

## Q5. Extract Second Row

### Output
```python
[4 5 6]
```


In [ ]:
# Write your code here

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix[1])

## Q6. Create DataFrame

| Name | Marks |
|------|------|
| Raj | 80 |
| Amit | 70 |
| Neha | 90 |
| Priya | 85 |


In [ ]:
# Write your code here
import pandas as pd
df = pd.DataFrame({
    'Name': ['Raj', 'Amit', 'Neha', 'Priya'],
    'Marks': [80, 70, 90, 85]
})
df

## Q7. Add Bonus Column

Bonus = Marks + 5

### Expected Output
```
Raj    80   85
Amit   70   75
Neha   90   95
Priya  85   90
```


In [ ]:
# Write your code here

df['Bonus'] = df['Marks'] + 5
df

## Q8. Display Students Having Marks > 80

### Expected Output
```
Neha   90
Priya  85
```


In [ ]:
# Write your code here

print(df[df['Marks'] > 80])

## Q9. Print First Row Using iloc

### Expected Output
```
Raj 80
```


In [ ]:
# Write your code here

df = pd.DataFrame({
    'Name': ['Raj', 'Amit', 'Neha', 'Priya'],
    'Marks': [80, 70, 90, 85]
})
print(df.iloc[0])

## Q10. Print Third Row Using iloc

### Expected Output
```
Neha 90
```


In [ ]:
# Write your code here
print(df.iloc[2])

## Q11. Print First 2 Rows Using iloc

### Expected Output
```
Raj 80
Amit 70
```


In [ ]:
# Write your code here

print(df.iloc[:2])

## Q12. Print Only Name Column Using iloc

### Expected Output
```
Raj
Amit
Neha
Priya
```


In [ ]:
# Write your code here

print(df.iloc[:,0])

## Q13. Update Amit's Marks to 75

### Expected Output
```
Amit 75
```


In [ ]:
# Write your code here

df.loc[1, 'Marks'] = 75
print(df.iloc[1])

## Q14. Sort DataFrame by Marks (Descending)

### Expected Output
```
Neha  90
Priya 85
Raj   80
Amit  75
```


In [ ]:
# Write your code here

print(df.sort_values(by='Marks', ascending=False))