
# NumPy Assignment — Array Operations, Broadcasting & Aggregate Functions




# Q1. Array Addition

## Problem Statement
Create two NumPy arrays:

```python
arr1 = [1, 2, 3, 4]
arr2 = [10, 20, 30, 40]
```

Add both arrays element-wise.

## Sample Output
```python
[11 22 33 44]
```


In [ ]:
# Write your code here

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])
print(arr1 + arr2)


# Q2. Array Multiplication

## Problem Statement
Create two NumPy arrays and multiply them element-wise.

## Sample Input
```python
arr1 = [2, 4, 6]
arr2 = [3, 5, 7]
```

## Sample Output
```python
[ 6 20 42]
```


In [ ]:
# Write your code here

arr1 = np.array([2,4,6])
arr2 = np.array([3,5,7])
print(arr1 * arr2)


# Q3. Add a Scalar to an Array

## Problem Statement
Create the array:

```python
[10, 20, 30, 40]
```

Add 5 to every element using broadcasting.

## Sample Output
```python
[15 25 35 45]
```


In [ ]:
# Write your code here

arr = np.array([10,20,30,40])
print(arr + 5)


# Q4. Multiply Array by a Scalar

## Problem Statement
Multiply every element of the array by 3.

## Sample Input
```python
[1, 2, 3, 4]
```

## Sample Output
```python
[ 3  6  9 12]
```


In [ ]:
# Write your code here

arr = np.array([1,2,3,4])
print(arr * 3)


# Q5. Matrix Broadcasting

## Problem Statement
Create a 2×3 array and add 10 to every element.

## Sample Input
```python
[[1,2,3],
 [4,5,6]]
```

## Sample Output
```python
[[11 12 13]
 [14 15 16]]
```


In [ ]:
# Write your code here

arr = np.array([[1,2,3],[4,5,6]])
print(arr + 10)


# Q6. Find Sum of Array

## Problem Statement
Create the array:

```python
[5, 10, 15, 20]
```

Find the sum of all elements.

## Sample Output
```python
50
```


In [ ]:
# Write your code here

arr = np.array([5,10,15,20])
print(arr.sum())


# Q7. Find Mean of Array

## Problem Statement
Create the array:

```python
[10, 20, 30, 40, 50]
```

Find the average value.

## Sample Output
```python
30.0
```


In [ ]:
# Write your code here

arr = np.array([10,20,30,40,50])
print(arr.mean())


# Q8. Find Maximum and Minimum Value

## Problem Statement
Create the array:

```python
[12, 45, 7, 89, 23]
```

Print:
- Maximum Value
- Minimum Value

## Sample Output
```python
Maximum: 89
Minimum: 7
```


In [ ]:
# Write your code here

arr = np.array([12,45,7,89,23])
print(f'Maximum: {arr.max()}')
print(f'Minimum: {arr.min()}')


# Q9. Row-wise Sum using Axis

## Problem Statement
Create the array:

```python
[[1,2,3],
 [4,5,6]]
```

Find row-wise sum using axis.

## Sample Output
```python
[ 6 15]
```


In [ ]:
# Write your code here

arr = np.array([[1,2,3],[4,5,6]])
print(arr.sum(axis=1))


# Q10. Column-wise Sum using Axis

## Problem Statement
Create the array:

```python
[[1,2,3],
 [4,5,6]]
```

Find column-wise sum using axis.

## Sample Output
```python
[5 7 9]
```


In [ ]:
# Write your code here
arr = np.array([[1,2,3],[4,5,6]])
print(arr.sum(axis=0))